---
- hosts: all
  become: yes
  become_user: root
  hosts: 127.0.0.1
  connection: local
  become_method: sudo
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest
    - name: Start Nginx
      service: name=nginx state=started
    - name: Print hello
      template: src=nginx.conf dest=/etc/nginx/nginx.conf
